spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  # for schema.sql
  sql:
    init:
      mode: always

  # SQL Log
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        

map-api:
  conformKey: ${DEV_MAP_API_CONFORM_KEY}