spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # MyBatis SQL 로그 찍기
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  # for schema.sql
  sql:
    init:
      mode: always
        
# 주소 검색 API 승인키
map-api:
  conformKey: ${DEV_MAP_API_CONFORM_KEY}
  
# 파일 저장 경로
file:
  dir: C:\Users\Rody\eclipse-workspace\board-bucket\

# 로그 레벨 설정
logging:
  level:
    jdbc.sqlonly: DEBUG